name: SteamWorks.ext Build

on:
  push:
    branches: [ x64 ]
  pull_request:
    branches: [ x64 ]
  schedule:
    - cron: "30 0 1 */3 *"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ 3.11 ]
        # Ubuntu 24.04 builds will be available until the end of 2029.
        # Ubuntu 22.04 builds will be available until the end of 2027.
        os: [ windows-latest, ubuntu-24.04, ubuntu-22.04 ]
        sm-version: [ "1.12-dev", "1.13-dev" ]
        arch: [ "x86_64", "x86" ]
        exclude:
          - sm-version: "1.12-dev"
            arch: "x86"

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Deps
      if: runner.os == 'Linux'
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get install bash lib32z1-dev libc6-dev-i386
        sudo apt-get install g++-multilib
    - name: Update Clang (ubuntu-22.04 only)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-15
    - uses: actions/checkout@v6
      name: Clone AMBuild
      with:
        repository: 'alliedmodders/ambuild'
        path: 'assets/ambuild'
    - name: install AMBuild
      run: pip install ./assets/ambuild
    - uses: actions/checkout@v6
      name: Clone SteamworksSDK
      with:
        repository: 'irql-notlessorequal/SteamworksSDK'
        path: 'assets/SteamworksSDK'
        token: ${{ secrets.STEAMWORKS_SDK_OAUTH }}
    - uses: actions/checkout@v6
      name: Clone hl2sdk-sdk2013
      with:
        repository: 'alliedmodders/hl2sdk'
        ref: 'sdk2013'
        path: 'assets/hl2sdk-sdk2013'
    - uses: actions/checkout@v6
      name: Clone Metamod Source
      with:
        repository: 'alliedmodders/metamod-source'
        ref: ${{ matrix.sm-version == '1.13-dev' && 'master' || matrix.sm-version }}
        path: 'assets/mmsource-central'
    - uses: actions/checkout@v6
      name: Clone Sourcemod
      with:
        repository: 'alliedmodders/sourcemod'
        submodules: recursive
        ref: ${{ matrix.sm-version == '1.13-dev' && 'master' || matrix.sm-version }}
        path: 'assets/sourcemod-central'
    - name: Create redundant AMBuildScript
      run: cp AMBuildScript ../
    - name: Run build script
      run: |
        cd build
        bash ./build ${{ matrix.arch }}
    - uses: actions/upload-artifact@v6
      name: Upload build artifacts
      with:
        name: "steamworks-${{ matrix.arch == 'x86_64' && 'x64' || 'x86' }}-${{ matrix.sm-version }}-${{ matrix.os }}-git"
        path: build/package/
        if-no-files-found: error
        retention-days: 90

  build-info:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Summary
      run: |
        cat <<'EOF' >> $GITHUB_STEP_SUMMARY

        ```
        steamworks-x64-1.12-dev-ubuntu-22.04-git
                    │     │           │
                    │     │           └─ Build OS
                    │     └─ SourceMod Version
                    └─ SourceMod Architecture
        ```

        > [!NOTE]
        > `ubuntu-22.04` requires glibc >= 2.35, `ubuntu-24.04` requires glibc >= 2.39
        
        > [!IMPORTANT]
        > For 32-bit builds, only the latest version of SourceMod is supported.
        EOF